# Generated by Django 4.2.5 on 2025-07-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_remove_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
