# Generated by Django 4.2.5 on 2025-08-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
