# Generated by Django 4.2.5 on 2025-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attendance_timestamp_alter_person_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
