# Generated by Django 4.2.5 on 2025-08-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_person_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='embedding',
        ),
    ]
