# Generated by Django 4.2.5 on 2025-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_person_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
