# Generated by Django 4.2.5 on 2025-09-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attendance_time_in_am_attendance_time_in_pm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
