# Generated by Django 4.2.5 on 2025-09-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attendance_remarks_excuseletter_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excuseletter',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='excuseletter',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excuseletter',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
