# Generated by Django 4.2.5 on 2025-09-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_excuseletter_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuseletter',
            name='submitted_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
